#!/usr/bin/env python
import sys, os

components = ['gtest', '..']

recurse = lambda ctx : map(lambda proj: ctx.recurse(proj), components)

def options(opt):
    recurse(opt)

def configure(cfg):
    recurse(cfg)

    cfg.env.INCLUDES_BITTER_TEST = ['.',]
    cfg.env.CXXFLAGS_BITTER_TEST = [
            '-O1',
            '-g',
            '-std=c++0x',
            '-Wall',
            '-Wextra',
            '-pedantic',
        ]

def build(bld):
    recurse(bld)

    bld.program(
        source       = bld.path.ant_glob('*.cc'),
        target       = 'main',
        use          = [
            'BITTER_TEST',
            'bitter',
            'gtest',
            ],
        install_path = 'bin',
    )

