#!/usr/bin/env python
import sys, os

components = ['gtest', '..']

recurse = lambda ctx : map(lambda proj: ctx.recurse(proj), components)

def options(opt):
    recurse(opt)

def configure(cfg):
    recurse(cfg)

    # use $PWD as default prefix for tests, if no prefix is given explicitly
    cfg.env.PREFIX = cfg.env.PREFIX if os.getenv('PREFIX') else cfg.path.abspath()

def build(bld):
    recurse(bld)

    bld.program(
        source       = bld.path.ant_glob('*.cc'),
        target       = 'main',
        includes     = '.',
        install_path = 'bin',
        use          = ['bitter', 'gtest'],
        cxxflags     = [
                '-O1',
                '-g',
                '-std=c++0x',
                '-Wall',
                '-Wextra',
                '-pedantic',
                #'-DBITTER_NO_RANGE_CHECK',
            ],
    )
